---
title: "welcome to my blog"
date:2018-08-06
---

title: The FUTURE IS COMING
author: PHILIP
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The is bullshit
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
